Add ftmetadata endpoint
mynearwallet/near-contract-helper pull request #23
Opened 2022-10-12 13:59 UTC by followdarko

https://mnw.atlassian.net/browse/MNW-224

Обсуждение:
https://mynearwallet.slack.com/archives/C03EY651XBR/p1665572564797669
https://mynearwallet.slack.com/archives/C03TNKKT267/p1665581693083169

TODO:
* Править документацию
* Запустить ВСЁ-ТАКИ локально и протестировать

2022-10-12 14:31 UTC, loosefer commented on src/handlers/tokens.js
> +        await Promise.all(tokensArray.map(async (token) => {
Давай добавим проверку Array.isArray чтобы заведомо не ходить в .map не массива.

2022-10-12 14:31 UTC, loosefer commented on src/handlers/tokens.js
> +        result: JSON.stringify(result)
Не очень понял, задача стоит вроде как сделать кэш, или еще не готово? 
Если нет, ставь [WIP] в шапку плз чтобы было понятней.

2022-10-12 14:31 UTC, loosefer commented on src/handlers/tokens.js
> +        result: JSON.stringify(result)
Если что, у меня есть оч простая версия in-memory кеша вот тут.
https://github.com/mynearwallet/mynearwallet-confidant/blob/master/src/store/cache/index.ts

2022-10-12 14:31 UTC, loosefer commented on src/handlers/tokens.js
> +        const tokensArray = JSON.parse(tokens);
Мне кажется tokens окей нейминг, без array

2022-10-12 14:31 UTC, loosefer commented on src/handlers/tokens.js
> +        const account = await ctx.near.account('dontcare');
account можно проинициализровать за пределами области видимости и сделать константой, не инитить на каждый запрос.

2022-10-12 14:31 UTC, loosefer commented on src/handlers/tokens.js
> +                token,
Чёт я переживаю что сюда можно адрес вообще любого контракта пропихнуть и вызов может быть совершен от имени сервера на тот контракт который укажет инициатор запроса, но аккаунт вроде как dontcare и нам это наврядли чем-то может грозить. 🤔

2022-10-12 14:40 UTC, PinkiNice commented on src/handlers/tokens.js
> +        result: JSON.stringify(result)
We should use node-cache implementation instead of a custom one. 
It is already installed in contract-helper and ready to be used

2022-10-12 14:40 UTC, PinkiNice commented on app.js
> +const { getFtMetadata } = require('./src/handlers/tokens');
Lets move this to indexer.js

2022-10-14 10:50 UTC, followdarko commented on src/handlers/tokens.js
> +        const tokensArray = JSON.parse(tokens);
оно ж выше уже занято

2022-10-14 10:50 UTC, followdarko commented on src/handlers/tokens.js
> +        const account = await ctx.near.account('dontcare');
Вынес в отдельный мидлвар, спасибо!

2022-10-14 13:07 UTC, PinkiNice commented on src/handlers/tokens.js
> +            await Promise.allSettled(tokensArray.map(async (token) => {
Can someone DDOS this endpoint by just passing a shit-ton of non-existent [tokens] ?

Can it be fixed by throwing on first error and not making all the requests?

2022-10-14 13:07 UTC, PinkiNice commented on src/handlers/tokens.js
> +            await Promise.allSettled(tokensArray.map(async (token) => {
Promise.allSettled never throws - it makes sense to remove it from "try" clause to avoid confusion

2022-10-14 13:07 UTC, PinkiNice commented on src/handlers/tokens.js
> +    } catch (err) {
I guess we should return something in case of an error?

2022-10-14 13:07 UTC, PinkiNice commented on test/handlers/tokens.test.js
> +        await request
Lets split those tests into multiple cases - seems like cases are checking different outcomes here

2022-10-14 13:07 UTC, PinkiNice commented on src/middleware/near.js
> +const initDontCareAccount = async (ctx, next) => {
Lets rename it for easier understanding: initDontCareAccount gives no context without understanding of the function.
Maybe `initEmptyNearAccount` - as an example

2022-10-14 14:15 UTC, followdarko commented on src/handlers/tokens.js
> +            await Promise.allSettled(tokensArray.map(async (token) => {
Seems like yes.
If we will use Promise.all we get such behaviour, but all of the requests will still process on the background until the end. 
AbortController could help with this but need to dive deep

2022-10-14 14:16 UTC, NotEternal commented on src/middleware/near.js
> +const initDontCareAccount = async (ctx, next) => {
`initViewAccount` ?

As far as I know, the name for this isn't important. We can take anything, not only dontcare.

2022-10-14 14:18 UTC, followdarko commented on src/handlers/tokens.js
> +            await Promise.allSettled(tokensArray.map(async (token) => {
Actually it may throw error on `decodeURIComponent`

2022-10-14 14:20 UTC, followdarko commented on src/handlers/tokens.js
> +    } catch (err) {
Yep. Could't reproduce an error in the first time

2022-10-14 14:25 UTC, followdarko commented on src/middleware/near.js
> +const initDontCareAccount = async (ctx, next) => {
as you wish. naming here doesn't matter

2022-10-14 18:04 UTC, PinkiNice commented on src/handlers/tokens.js
> +            await Promise.allSettled(tokensArray.map(async (token) => {
Makes sense to put it in another try/catch and raise a specific error with a message like "Can't parse tokens list" or something

2022-10-14 18:05 UTC, PinkiNice commented on src/handlers/tokens.js
> +            await Promise.allSettled(tokensArray.map(async (token) => {
As this endpoint is not expected to make a lot of requests (99% should be handled from the cache) - we can setup a batch-load for tokens in batches of 3, for example.

2022-10-17 07:49 UTC, loosefer commented on src/handlers/tokens.js
> +        const tokensArray = JSON.parse(tokens);
`tokensList`

2022-10-17 07:53 UTC, loosefer commented on indexer.js
> +    module.exports = app.listen(8888);
`module.exports = app.listen(PORT);` ?

2022-10-17 11:29 UTC, followdarko commented on indexer.js
> +    module.exports = app.listen(8888);
tuned

2022-10-17 11:55 UTC, PinkiNice requested changes

2022-10-17 11:55 UTC, PinkiNice commented on test/handlers/tokens.test.js
> +    it('One of the tokens not exist', async () => {
Test names are hard to understand from console:
Suggest renaming:
"One of the tokens not exist" => "Handles non-existent token with grace"

2022-10-17 11:55 UTC, PinkiNice commented on src/handlers/tokens.js
> +    try {
Can we split this function into multiple smaller functions?
Hard to read for me.

Something like:
```
const rawTokens = parseTokenNamesFromURI(ctx.query)
const tokens = uniqueTokens(tokens)
const batches = arrayPartition(tokens, 25)
execBatch(batches, async (batch) => { //do logic })
```

2022-10-17 14:18 UTC, PinkiNice commented on src/handlers/tokens.js
> +    let chunkedList = [];
rename: chunks ?

2022-10-17 14:18 UTC, PinkiNice commented on src/handlers/tokens.js
> +function arrayPartition (tokens, size) {
This function is generic and not tied to "tokens" per se.

So more generaic arg name would fit there: tokens => array

2022-10-17 14:18 UTC, PinkiNice commented on src/handlers/tokens.js
> +async function execBatch (batches, callback) {
I feel something odd about "execBatch" naming, when the first parameter is "batches" (multiple).
Feels a bit counter-intuitive
Can we come up with a better naming here?

2022-10-17 14:18 UTC, PinkiNice commented on test/handlers/tokens.test.js
> +    it('Works as exprected', async () => {
typo: exprected => expected

2022-10-17 14:57 UTC, followdarko commented on src/handlers/tokens.js
> +    let chunkedList = [];
right

2022-10-17 15:09 UTC, PinkiNice approved these changes

2022-10-17 15:10 UTC, PinkiNice commented
Legit

2022-10-17 18:05 UTC, merged